# NHN SecureManager
secure-key-manager:
  url: https://api-keymanager.cloud.toast.com
  app-key: mcXcTmrnbRezlila
  local-key: gaship

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: 142ea0b649994beb8650736c271f5e13
  username: eggplant
  password: e55472d5d7ea4bbdb6f3149e1ed597e5

eggplant-delivery-server.url: http://192.168.71.34:8080

rabbitmq:
  host: b2d2bb80e0f843e396337084925a54fc
  port: 5672
  username: ea91066a691544fd98109e8eb7e6a494
  password: ff39e7234e55400ebf81feec38e1b64e

spring:
  batch:
    job:
      enabled: false