rabbitmq:
  host: b2d2bb80e0f843e396337084925a54fc
  port: 5672
  username: ea91066a691544fd98109e8eb7e6a494
  password: ff39e7234e55400ebf81feec38e1b64e

# NHN SecureManager
secure-key-manager:
  url: https://api-keymanager.cloud.toast.com
  app-key: mcXcTmrnbRezlila
  local-key: gaship

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true

  profiles:
    group:
      local: "common, testdb"
      dev: "common, devdb"
      prod: "common, proddb"
  batch:
    job:
      enabled: false

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: 2016554d23614b28b1ffb17e68a0d640
  username: eggplant
  password: e55472d5d7ea4bbdb6f3149e1ed597e5

---

spring:
  config:
    activate:
      on-profile: "common"

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: 2016554d23614b28b1ffb17e68a0d640
  username: eggplant
  password: e55472d5d7ea4bbdb6f3149e1ed597e5

---

spring:
  config:
    activate:
      on-profile: "testdb"

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: 2016554d23614b28b1ffb17e68a0d640
  username: eggplant
  password: e55472d5d7ea4bbdb6f3149e1ed597e5

---

spring:
  config:
    activate:
      on-profile: "proddb"

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: 8fa7304edb474141a7197065bc5edfeb
  username: eggplant
  password: e55472d5d7ea4bbdb6f3149e1ed597e5
